// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dfs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WipeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WipeRequest) Reset()         { *m = WipeRequest{} }
func (m *WipeRequest) String() string { return proto.CompactTextString(m) }
func (*WipeRequest) ProtoMessage()    {}
func (*WipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{0}
}

func (m *WipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WipeRequest.Unmarshal(m, b)
}
func (m *WipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WipeRequest.Marshal(b, m, deterministic)
}
func (m *WipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WipeRequest.Merge(m, src)
}
func (m *WipeRequest) XXX_Size() int {
	return xxx_messageInfo_WipeRequest.Size(m)
}
func (m *WipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WipeRequest proto.InternalMessageInfo

type WipeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WipeResponse) Reset()         { *m = WipeResponse{} }
func (m *WipeResponse) String() string { return proto.CompactTextString(m) }
func (*WipeResponse) ProtoMessage()    {}
func (*WipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{1}
}

func (m *WipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WipeResponse.Unmarshal(m, b)
}
func (m *WipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WipeResponse.Marshal(b, m, deterministic)
}
func (m *WipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WipeResponse.Merge(m, src)
}
func (m *WipeResponse) XXX_Size() int {
	return xxx_messageInfo_WipeResponse.Size(m)
}
func (m *WipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WipeResponse proto.InternalMessageInfo

func (m *WipeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type HeartbeatRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{2}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *HeartbeatRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *HeartbeatRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type HeartbeatResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{3}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UploadRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize             int64    `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{4}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type UploadResponse struct {
	NodeIp               string   `protobuf:"bytes,1,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	NodePort             int32    `protobuf:"varint,2,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{5}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetNodeIp() string {
	if m != nil {
		return m.NodeIp
	}
	return ""
}

func (m *UploadResponse) GetNodePort() int32 {
	if m != nil {
		return m.NodePort
	}
	return 0
}

type DownloadRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{6}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type DownloadResponse struct {
	Locations            []*NodeLocation `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	FileSize             int64           `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{7}
}

func (m *DownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResponse.Unmarshal(m, b)
}
func (m *DownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResponse.Marshal(b, m, deterministic)
}
func (m *DownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResponse.Merge(m, src)
}
func (m *DownloadResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadResponse.Size(m)
}
func (m *DownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResponse proto.InternalMessageInfo

func (m *DownloadResponse) GetLocations() []*NodeLocation {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *DownloadResponse) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type NodeLocation struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeLocation) Reset()         { *m = NodeLocation{} }
func (m *NodeLocation) String() string { return proto.CompactTextString(m) }
func (*NodeLocation) ProtoMessage()    {}
func (*NodeLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{8}
}

func (m *NodeLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeLocation.Unmarshal(m, b)
}
func (m *NodeLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeLocation.Marshal(b, m, deterministic)
}
func (m *NodeLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeLocation.Merge(m, src)
}
func (m *NodeLocation) XXX_Size() int {
	return xxx_messageInfo_NodeLocation.Size(m)
}
func (m *NodeLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeLocation.DiscardUnknown(m)
}

var xxx_messageInfo_NodeLocation proto.InternalMessageInfo

func (m *NodeLocation) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NodeLocation) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type NotifyUploadRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FilePath             string   `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize             int64    `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyUploadRequest) Reset()         { *m = NotifyUploadRequest{} }
func (m *NotifyUploadRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyUploadRequest) ProtoMessage()    {}
func (*NotifyUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{9}
}

func (m *NotifyUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyUploadRequest.Unmarshal(m, b)
}
func (m *NotifyUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyUploadRequest.Marshal(b, m, deterministic)
}
func (m *NotifyUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyUploadRequest.Merge(m, src)
}
func (m *NotifyUploadRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyUploadRequest.Size(m)
}
func (m *NotifyUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyUploadRequest proto.InternalMessageInfo

func (m *NotifyUploadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *NotifyUploadRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NotifyUploadRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *NotifyUploadRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type NotifyUploadResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyUploadResponse) Reset()         { *m = NotifyUploadResponse{} }
func (m *NotifyUploadResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyUploadResponse) ProtoMessage()    {}
func (*NotifyUploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{10}
}

func (m *NotifyUploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyUploadResponse.Unmarshal(m, b)
}
func (m *NotifyUploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyUploadResponse.Marshal(b, m, deterministic)
}
func (m *NotifyUploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyUploadResponse.Merge(m, src)
}
func (m *NotifyUploadResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyUploadResponse.Size(m)
}
func (m *NotifyUploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyUploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyUploadResponse proto.InternalMessageInfo

func (m *NotifyUploadResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReplicateRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	SourceIp             string   `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort           int32    `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp        string   `protobuf:"bytes,4,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort      int32    `protobuf:"varint,5,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateRequest) Reset()         { *m = ReplicateRequest{} }
func (m *ReplicateRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicateRequest) ProtoMessage()    {}
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{11}
}

func (m *ReplicateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateRequest.Unmarshal(m, b)
}
func (m *ReplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateRequest.Marshal(b, m, deterministic)
}
func (m *ReplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateRequest.Merge(m, src)
}
func (m *ReplicateRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicateRequest.Size(m)
}
func (m *ReplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateRequest proto.InternalMessageInfo

func (m *ReplicateRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ReplicateRequest) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *ReplicateRequest) GetSourcePort() int32 {
	if m != nil {
		return m.SourcePort
	}
	return 0
}

func (m *ReplicateRequest) GetDestinationIp() string {
	if m != nil {
		return m.DestinationIp
	}
	return ""
}

func (m *ReplicateRequest) GetDestinationPort() int32 {
	if m != nil {
		return m.DestinationPort
	}
	return 0
}

type ReplicateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateResponse) Reset()         { *m = ReplicateResponse{} }
func (m *ReplicateResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicateResponse) ProtoMessage()    {}
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{12}
}

func (m *ReplicateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateResponse.Unmarshal(m, b)
}
func (m *ReplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateResponse.Marshal(b, m, deterministic)
}
func (m *ReplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateResponse.Merge(m, src)
}
func (m *ReplicateResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicateResponse.Size(m)
}
func (m *ReplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateResponse proto.InternalMessageInfo

func (m *ReplicateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReportFilesRequest struct {
	NodeId               string      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Files                []*FileInfo `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReportFilesRequest) Reset()         { *m = ReportFilesRequest{} }
func (m *ReportFilesRequest) String() string { return proto.CompactTextString(m) }
func (*ReportFilesRequest) ProtoMessage()    {}
func (*ReportFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{13}
}

func (m *ReportFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportFilesRequest.Unmarshal(m, b)
}
func (m *ReportFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportFilesRequest.Marshal(b, m, deterministic)
}
func (m *ReportFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportFilesRequest.Merge(m, src)
}
func (m *ReportFilesRequest) XXX_Size() int {
	return xxx_messageInfo_ReportFilesRequest.Size(m)
}
func (m *ReportFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportFilesRequest proto.InternalMessageInfo

func (m *ReportFilesRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ReportFilesRequest) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

type FileInfo struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize             int64    `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FilePath             string   `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{14}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileInfo) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileInfo) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type ReportFilesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportFilesResponse) Reset()         { *m = ReportFilesResponse{} }
func (m *ReportFilesResponse) String() string { return proto.CompactTextString(m) }
func (*ReportFilesResponse) ProtoMessage()    {}
func (*ReportFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{15}
}

func (m *ReportFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportFilesResponse.Unmarshal(m, b)
}
func (m *ReportFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportFilesResponse.Marshal(b, m, deterministic)
}
func (m *ReportFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportFilesResponse.Merge(m, src)
}
func (m *ReportFilesResponse) XXX_Size() int {
	return xxx_messageInfo_ReportFilesResponse.Size(m)
}
func (m *ReportFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportFilesResponse proto.InternalMessageInfo

func (m *ReportFilesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteFileRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{16}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type DeleteFileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{17}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllRequest) Reset()         { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()    {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{18}
}

func (m *DeleteAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllRequest.Unmarshal(m, b)
}
func (m *DeleteAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllRequest.Merge(m, src)
}
func (m *DeleteAllRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllRequest.Size(m)
}
func (m *DeleteAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllRequest proto.InternalMessageInfo

type DeleteAllResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllResponse) Reset()         { *m = DeleteAllResponse{} }
func (m *DeleteAllResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllResponse) ProtoMessage()    {}
func (*DeleteAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40f47c7d696b220, []int{19}
}

func (m *DeleteAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllResponse.Unmarshal(m, b)
}
func (m *DeleteAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllResponse.Merge(m, src)
}
func (m *DeleteAllResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllResponse.Size(m)
}
func (m *DeleteAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllResponse proto.InternalMessageInfo

func (m *DeleteAllResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*WipeRequest)(nil), "dfs.WipeRequest")
	proto.RegisterType((*WipeResponse)(nil), "dfs.WipeResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "dfs.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "dfs.HeartbeatResponse")
	proto.RegisterType((*UploadRequest)(nil), "dfs.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "dfs.UploadResponse")
	proto.RegisterType((*DownloadRequest)(nil), "dfs.DownloadRequest")
	proto.RegisterType((*DownloadResponse)(nil), "dfs.DownloadResponse")
	proto.RegisterType((*NodeLocation)(nil), "dfs.NodeLocation")
	proto.RegisterType((*NotifyUploadRequest)(nil), "dfs.NotifyUploadRequest")
	proto.RegisterType((*NotifyUploadResponse)(nil), "dfs.NotifyUploadResponse")
	proto.RegisterType((*ReplicateRequest)(nil), "dfs.ReplicateRequest")
	proto.RegisterType((*ReplicateResponse)(nil), "dfs.ReplicateResponse")
	proto.RegisterType((*ReportFilesRequest)(nil), "dfs.ReportFilesRequest")
	proto.RegisterType((*FileInfo)(nil), "dfs.FileInfo")
	proto.RegisterType((*ReportFilesResponse)(nil), "dfs.ReportFilesResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "dfs.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "dfs.DeleteFileResponse")
	proto.RegisterType((*DeleteAllRequest)(nil), "dfs.DeleteAllRequest")
	proto.RegisterType((*DeleteAllResponse)(nil), "dfs.DeleteAllResponse")
}

func init() {
	proto.RegisterFile("proto/dfs.proto", fileDescriptor_b40f47c7d696b220)
}

var fileDescriptor_b40f47c7d696b220 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x56, 0x9c, 0xb4, 0x4d, 0x26, 0xcd, 0xd7, 0xf6, 0xcb, 0xaf, 0xdf, 0x03, 0x95, 0x11, 0x52,
	0x10, 0x6a, 0x52, 0x85, 0x0b, 0x42, 0xe2, 0xbb, 0xaa, 0x88, 0x80, 0x52, 0x19, 0x10, 0x12, 0x97,
	0xb2, 0x8d, 0x27, 0xaa, 0x85, 0x6b, 0x2f, 0xde, 0xad, 0x10, 0xbd, 0xf3, 0x8f, 0xb8, 0xf3, 0x07,
	0xf8, 0x51, 0x68, 0xd7, 0xeb, 0x64, 0x6d, 0xa3, 0xba, 0xc0, 0x29, 0xf1, 0x33, 0x33, 0xcf, 0xcc,
	0xf8, 0x99, 0x19, 0x43, 0x8f, 0x25, 0xb1, 0x88, 0xc7, 0xfe, 0x9c, 0x8f, 0xd4, 0x3f, 0x52, 0xf7,
	0xe7, 0xdc, 0xed, 0x40, 0xfb, 0x7d, 0xc0, 0xd0, 0xc3, 0xcf, 0x17, 0xc8, 0x85, 0x3b, 0x84, 0xf5,
	0xf4, 0x91, 0xb3, 0x38, 0xe2, 0x48, 0x6c, 0x58, 0xe3, 0x17, 0xb3, 0x19, 0x72, 0x6e, 0xd7, 0x76,
	0x6b, 0xc3, 0xa6, 0x97, 0x3d, 0xba, 0xaf, 0xa1, 0xff, 0x1c, 0x69, 0x22, 0x4e, 0x91, 0x0a, 0x1d,
	0x4d, 0x76, 0x60, 0x2d, 0x8a, 0x7d, 0x3c, 0x09, 0x7c, 0xe5, 0xdd, 0xf2, 0x56, 0xe5, 0xe3, 0xd4,
	0x27, 0x5d, 0xb0, 0x02, 0x66, 0x5b, 0x0a, 0xb3, 0x02, 0x46, 0x08, 0x34, 0x58, 0x9c, 0x08, 0xbb,
	0xbe, 0x5b, 0x1b, 0xae, 0x78, 0xea, 0xbf, 0xbb, 0x07, 0x03, 0x83, 0xb0, 0x32, 0xff, 0x14, 0x3a,
	0xef, 0x58, 0x18, 0x53, 0x3f, 0x4b, 0xfe, 0x3f, 0xb4, 0xe6, 0x41, 0x88, 0x27, 0x11, 0x3d, 0x47,
	0x9d, 0xbe, 0x29, 0x81, 0x23, 0x7a, 0x8e, 0x0b, 0x23, 0x0f, 0x2e, 0x51, 0xd5, 0x51, 0x4f, 0x8d,
	0x6f, 0x82, 0x4b, 0x74, 0x0f, 0xa1, 0x9b, 0x51, 0xe9, 0xb4, 0x8b, 0x46, 0x58, 0xae, 0x11, 0x26,
	0x79, 0x94, 0x41, 0x55, 0x6f, 0xa9, 0xea, 0x9b, 0x12, 0x38, 0x96, 0x1d, 0x8c, 0xa0, 0x77, 0x10,
	0x7f, 0x89, 0xae, 0x5b, 0x94, 0xfb, 0x11, 0xfa, 0x4b, 0x7f, 0x9d, 0x79, 0x0c, 0xad, 0x30, 0x9e,
	0x51, 0x11, 0xc4, 0x91, 0x6c, 0xb9, 0x3e, 0x6c, 0x4f, 0x06, 0x23, 0xa9, 0xd9, 0x51, 0xec, 0xe3,
	0x4b, 0x6d, 0xf1, 0x96, 0x3e, 0x57, 0x77, 0x36, 0x81, 0x75, 0x33, 0x4e, 0xeb, 0x50, 0x2b, 0xe9,
	0x60, 0x19, 0x3a, 0x7c, 0xab, 0xc1, 0xc6, 0x51, 0x2c, 0x82, 0xf9, 0xd7, 0x3f, 0x78, 0xbf, 0x86,
	0xf2, 0x56, 0x4e, 0xf9, 0x2c, 0x8a, 0x51, 0x71, 0xa6, 0xe4, 0xd6, 0x51, 0xc7, 0x54, 0x9c, 0xe5,
	0x6b, 0x6f, 0x14, 0x6a, 0xdf, 0x87, 0xcd, 0x7c, 0x19, 0x95, 0x23, 0xf1, 0xa3, 0x06, 0x7d, 0x0f,
	0x59, 0x18, 0xcc, 0xa8, 0xc0, 0xeb, 0x8e, 0x05, 0x8f, 0x2f, 0x92, 0x99, 0x52, 0x3a, 0x2d, 0xbc,
	0x99, 0x02, 0x53, 0x46, 0x6e, 0x40, 0x5b, 0x1b, 0x8d, 0x59, 0x85, 0x14, 0x92, 0x7a, 0x93, 0x5b,
	0xd0, 0xf5, 0x91, 0x8b, 0x20, 0x52, 0x2f, 0x57, 0x52, 0x34, 0x14, 0x45, 0xc7, 0x40, 0xa7, 0x8c,
	0xdc, 0x86, 0xbe, 0xe9, 0xa6, 0xc8, 0x56, 0x14, 0x59, 0xcf, 0xc0, 0x8f, 0xf5, 0x0e, 0x18, 0x0d,
	0x54, 0x36, 0xec, 0x01, 0xf1, 0x50, 0xf2, 0x1d, 0x06, 0x21, 0xf2, 0xca, 0x2d, 0xbc, 0x09, 0x2b,
	0xb2, 0x73, 0x6e, 0x5b, 0x6a, 0xae, 0x3a, 0x6a, 0xae, 0x64, 0xe8, 0x34, 0x9a, 0xc7, 0x5e, 0x6a,
	0x73, 0x29, 0x34, 0x33, 0xe8, 0xef, 0x57, 0xea, 0x4a, 0xd9, 0xdd, 0x31, 0x6c, 0xe4, 0xca, 0xae,
	0xec, 0x73, 0x1f, 0x06, 0x07, 0x18, 0xa2, 0x40, 0x19, 0x70, 0xad, 0xd5, 0x1a, 0x01, 0x31, 0x23,
	0x2a, 0x33, 0x10, 0xe8, 0xa7, 0xfe, 0x4f, 0xc2, 0x30, 0xbb, 0x85, 0x7b, 0x59, 0x56, 0x85, 0x55,
	0x51, 0x4c, 0x7e, 0xd6, 0xa1, 0xf3, 0x8a, 0x72, 0x81, 0xc9, 0xdb, 0x84, 0xce, 0x3e, 0x61, 0x42,
	0xee, 0x43, 0x6b, 0x71, 0xd1, 0xc8, 0x96, 0x7a, 0xdb, 0xc5, 0x93, 0xe9, 0x6c, 0x17, 0x61, 0x9d,
	0xe7, 0x1e, 0x74, 0xb4, 0x4b, 0x3a, 0xfe, 0x84, 0x28, 0xc7, 0xdc, 0x4a, 0x3a, 0x1b, 0x39, 0x4c,
	0x47, 0x3e, 0x84, 0x9e, 0xb6, 0x67, 0xc7, 0x85, 0x6c, 0x2a, 0xbf, 0xc2, 0x6d, 0x72, 0xb6, 0x0a,
	0xa8, 0x8e, 0x7f, 0x26, 0x6f, 0xc6, 0x72, 0xef, 0x88, 0xad, 0xcf, 0x4f, 0xe9, 0x22, 0x38, 0xff,
	0xfd, 0xc6, 0xa2, 0x49, 0x1e, 0x43, 0xdb, 0x90, 0x98, 0xec, 0x28, 0xcf, 0xf2, 0xac, 0x3a, 0x76,
	0xd9, 0xa0, 0x19, 0x1e, 0x00, 0x2c, 0x15, 0x24, 0xe9, 0x6b, 0x2a, 0x0d, 0x81, 0xb3, 0x53, 0xc2,
	0x75, 0xf8, 0x23, 0xe8, 0x2e, 0xc4, 0x4b, 0x6b, 0xd8, 0x32, 0x5c, 0x97, 0x2a, 0x3b, 0xdb, 0x45,
	0x38, 0x25, 0x98, 0x7c, 0xaf, 0x01, 0x1c, 0x50, 0x41, 0x5f, 0x20, 0xb2, 0x54, 0xcb, 0xc5, 0x66,
	0x6a, 0xaa, 0xe2, 0xa9, 0xd1, 0x54, 0xe5, 0x05, 0xfe, 0xc7, 0x56, 0xee, 0x40, 0x43, 0x7e, 0x93,
	0x49, 0x5f, 0x39, 0x18, 0x5f, 0x6b, 0x67, 0x60, 0x20, 0xa9, 0xf3, 0xd3, 0xd6, 0x87, 0xb5, 0xd1,
	0x58, 0x7d, 0xdf, 0x4f, 0x57, 0xd5, 0xcf, 0xdd, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0x88,
	0xbf, 0x9f, 0xf9, 0x07, 0x00, 0x00,
}
