// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: proto/dfs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MasterTracker_Heartbeat_FullMethodName              = "/dfs.MasterTracker/Heartbeat"
	MasterTracker_RequestUpload_FullMethodName          = "/dfs.MasterTracker/RequestUpload"
	MasterTracker_WaitForUpload_FullMethodName          = "/dfs.MasterTracker/WaitForUpload"
	MasterTracker_RequestDownload_FullMethodName        = "/dfs.MasterTracker/RequestDownload"
	MasterTracker_ListFiles_FullMethodName              = "/dfs.MasterTracker/ListFiles"
	MasterTracker_NotifyUpload_FullMethodName           = "/dfs.MasterTracker/NotifyUpload"
	MasterTracker_ReportFiles_FullMethodName            = "/dfs.MasterTracker/ReportFiles"
	MasterTracker_ReportTransferProgress_FullMethodName = "/dfs.MasterTracker/ReportTransferProgress"
	MasterTracker_DeleteFile_FullMethodName             = "/dfs.MasterTracker/DeleteFile"
	MasterTracker_DeleteAllFiles_FullMethodName         = "/dfs.MasterTracker/DeleteAllFiles"
)

// MasterTrackerClient is the client API for MasterTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterTrackerClient interface {
	// Data Keeper -> Master Tracker: heartbeat to signal liveness.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Client -> Master Tracker: request a data keeper to receive an upload.
	RequestUpload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
	// Client -> Master Tracker: wait for the data keeper to confirm storage.
	WaitForUpload(ctx context.Context, in *WaitForUploadRequest, opts ...grpc.CallOption) (*WaitForUploadResponse, error)
	// Client -> Master Tracker: request locations to download a file from.
	RequestDownload(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	// Client -> Master Tracker: list all known files.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// Data Keeper -> Master Tracker: notify that a file was stored locally.
	NotifyUpload(ctx context.Context, in *NotifyUploadRequest, opts ...grpc.CallOption) (*NotifyUploadResponse, error)
	// Data Keeper -> Master Tracker: report local files on startup.
	ReportFiles(ctx context.Context, in *ReportFilesRequest, opts ...grpc.CallOption) (*ReportFilesResponse, error)
	// Data Keeper -> Master Tracker: report replication transfer progress.
	ReportTransferProgress(ctx context.Context, in *TransferProgressRequest, opts ...grpc.CallOption) (*TransferProgressResponse, error)
	// Optional extension: delete a file across the cluster.
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	// Optional extension: wipe all files across the cluster.
	DeleteAllFiles(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error)
}

type masterTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterTrackerClient(cc grpc.ClientConnInterface) MasterTrackerClient {
	return &masterTrackerClient{cc}
}

func (c *masterTrackerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MasterTracker_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) RequestUpload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, MasterTracker_RequestUpload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) WaitForUpload(ctx context.Context, in *WaitForUploadRequest, opts ...grpc.CallOption) (*WaitForUploadResponse, error) {
	out := new(WaitForUploadResponse)
	err := c.cc.Invoke(ctx, MasterTracker_WaitForUpload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) RequestDownload(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, MasterTracker_RequestDownload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, MasterTracker_ListFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) NotifyUpload(ctx context.Context, in *NotifyUploadRequest, opts ...grpc.CallOption) (*NotifyUploadResponse, error) {
	out := new(NotifyUploadResponse)
	err := c.cc.Invoke(ctx, MasterTracker_NotifyUpload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) ReportFiles(ctx context.Context, in *ReportFilesRequest, opts ...grpc.CallOption) (*ReportFilesResponse, error) {
	out := new(ReportFilesResponse)
	err := c.cc.Invoke(ctx, MasterTracker_ReportFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) ReportTransferProgress(ctx context.Context, in *TransferProgressRequest, opts ...grpc.CallOption) (*TransferProgressResponse, error) {
	out := new(TransferProgressResponse)
	err := c.cc.Invoke(ctx, MasterTracker_ReportTransferProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, MasterTracker_DeleteFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerClient) DeleteAllFiles(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error) {
	out := new(DeleteAllResponse)
	err := c.cc.Invoke(ctx, MasterTracker_DeleteAllFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterTrackerServer is the server API for MasterTracker service.
// All implementations must embed UnimplementedMasterTrackerServer
// for forward compatibility
type MasterTrackerServer interface {
	// Data Keeper -> Master Tracker: heartbeat to signal liveness.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Client -> Master Tracker: request a data keeper to receive an upload.
	RequestUpload(context.Context, *UploadRequest) (*UploadResponse, error)
	// Client -> Master Tracker: wait for the data keeper to confirm storage.
	WaitForUpload(context.Context, *WaitForUploadRequest) (*WaitForUploadResponse, error)
	// Client -> Master Tracker: request locations to download a file from.
	RequestDownload(context.Context, *DownloadRequest) (*DownloadResponse, error)
	// Client -> Master Tracker: list all known files.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// Data Keeper -> Master Tracker: notify that a file was stored locally.
	NotifyUpload(context.Context, *NotifyUploadRequest) (*NotifyUploadResponse, error)
	// Data Keeper -> Master Tracker: report local files on startup.
	ReportFiles(context.Context, *ReportFilesRequest) (*ReportFilesResponse, error)
	// Data Keeper -> Master Tracker: report replication transfer progress.
	ReportTransferProgress(context.Context, *TransferProgressRequest) (*TransferProgressResponse, error)
	// Optional extension: delete a file across the cluster.
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	// Optional extension: wipe all files across the cluster.
	DeleteAllFiles(context.Context, *DeleteAllRequest) (*DeleteAllResponse, error)
	mustEmbedUnimplementedMasterTrackerServer()
}

// UnimplementedMasterTrackerServer must be embedded to have forward compatible implementations.
type UnimplementedMasterTrackerServer struct {
}

func (UnimplementedMasterTrackerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMasterTrackerServer) RequestUpload(context.Context, *UploadRequest) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUpload not implemented")
}
func (UnimplementedMasterTrackerServer) WaitForUpload(context.Context, *WaitForUploadRequest) (*WaitForUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForUpload not implemented")
}
func (UnimplementedMasterTrackerServer) RequestDownload(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDownload not implemented")
}
func (UnimplementedMasterTrackerServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedMasterTrackerServer) NotifyUpload(context.Context, *NotifyUploadRequest) (*NotifyUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyUpload not implemented")
}
func (UnimplementedMasterTrackerServer) ReportFiles(context.Context, *ReportFilesRequest) (*ReportFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportFiles not implemented")
}
func (UnimplementedMasterTrackerServer) ReportTransferProgress(context.Context, *TransferProgressRequest) (*TransferProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTransferProgress not implemented")
}
func (UnimplementedMasterTrackerServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedMasterTrackerServer) DeleteAllFiles(context.Context, *DeleteAllRequest) (*DeleteAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllFiles not implemented")
}
func (UnimplementedMasterTrackerServer) mustEmbedUnimplementedMasterTrackerServer() {}

// UnsafeMasterTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterTrackerServer will
// result in compilation errors.
type UnsafeMasterTrackerServer interface {
	mustEmbedUnimplementedMasterTrackerServer()
}

func RegisterMasterTrackerServer(s grpc.ServiceRegistrar, srv MasterTrackerServer) {
	s.RegisterService(&MasterTracker_ServiceDesc, srv)
}

func _MasterTracker_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_RequestUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).RequestUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_RequestUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).RequestUpload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_WaitForUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).WaitForUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_WaitForUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).WaitForUpload(ctx, req.(*WaitForUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_RequestDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).RequestDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_RequestDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).RequestDownload(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_NotifyUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).NotifyUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_NotifyUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).NotifyUpload(ctx, req.(*NotifyUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_ReportFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).ReportFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_ReportFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).ReportFiles(ctx, req.(*ReportFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_ReportTransferProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).ReportTransferProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_ReportTransferProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).ReportTransferProgress(ctx, req.(*TransferProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTracker_DeleteAllFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServer).DeleteAllFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTracker_DeleteAllFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServer).DeleteAllFiles(ctx, req.(*DeleteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterTracker_ServiceDesc is the grpc.ServiceDesc for MasterTracker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterTracker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.MasterTracker",
	HandlerType: (*MasterTrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _MasterTracker_Heartbeat_Handler,
		},
		{
			MethodName: "RequestUpload",
			Handler:    _MasterTracker_RequestUpload_Handler,
		},
		{
			MethodName: "WaitForUpload",
			Handler:    _MasterTracker_WaitForUpload_Handler,
		},
		{
			MethodName: "RequestDownload",
			Handler:    _MasterTracker_RequestDownload_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _MasterTracker_ListFiles_Handler,
		},
		{
			MethodName: "NotifyUpload",
			Handler:    _MasterTracker_NotifyUpload_Handler,
		},
		{
			MethodName: "ReportFiles",
			Handler:    _MasterTracker_ReportFiles_Handler,
		},
		{
			MethodName: "ReportTransferProgress",
			Handler:    _MasterTracker_ReportTransferProgress_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _MasterTracker_DeleteFile_Handler,
		},
		{
			MethodName: "DeleteAllFiles",
			Handler:    _MasterTracker_DeleteAllFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dfs.proto",
}

const (
	DataKeeper_Replicate_FullMethodName  = "/dfs.DataKeeper/Replicate"
	DataKeeper_DeleteFile_FullMethodName = "/dfs.DataKeeper/DeleteFile"
	DataKeeper_Wipe_FullMethodName       = "/dfs.DataKeeper/Wipe"
)

// DataKeeperClient is the client API for DataKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataKeeperClient interface {
	// Master Tracker -> Data Keeper: instruct a source keeper to copy a file.
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
	// Optional extension: delete a local file.
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	// Optional extension: wipe local storage.
	Wipe(ctx context.Context, in *WipeRequest, opts ...grpc.CallOption) (*WipeResponse, error)
}

type dataKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewDataKeeperClient(cc grpc.ClientConnInterface) DataKeeperClient {
	return &dataKeeperClient{cc}
}

func (c *dataKeeperClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, DataKeeper_Replicate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataKeeperClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, DataKeeper_DeleteFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataKeeperClient) Wipe(ctx context.Context, in *WipeRequest, opts ...grpc.CallOption) (*WipeResponse, error) {
	out := new(WipeResponse)
	err := c.cc.Invoke(ctx, DataKeeper_Wipe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataKeeperServer is the server API for DataKeeper service.
// All implementations must embed UnimplementedDataKeeperServer
// for forward compatibility
type DataKeeperServer interface {
	// Master Tracker -> Data Keeper: instruct a source keeper to copy a file.
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
	// Optional extension: delete a local file.
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	// Optional extension: wipe local storage.
	Wipe(context.Context, *WipeRequest) (*WipeResponse, error)
	mustEmbedUnimplementedDataKeeperServer()
}

// UnimplementedDataKeeperServer must be embedded to have forward compatible implementations.
type UnimplementedDataKeeperServer struct {
}

func (UnimplementedDataKeeperServer) Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedDataKeeperServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedDataKeeperServer) Wipe(context.Context, *WipeRequest) (*WipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Wipe not implemented")
}
func (UnimplementedDataKeeperServer) mustEmbedUnimplementedDataKeeperServer() {}

// UnsafeDataKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataKeeperServer will
// result in compilation errors.
type UnsafeDataKeeperServer interface {
	mustEmbedUnimplementedDataKeeperServer()
}

func RegisterDataKeeperServer(s grpc.ServiceRegistrar, srv DataKeeperServer) {
	s.RegisterService(&DataKeeper_ServiceDesc, srv)
}

func _DataKeeper_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataKeeper_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataKeeper_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataKeeper_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataKeeper_Wipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperServer).Wipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataKeeper_Wipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperServer).Wipe(ctx, req.(*WipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataKeeper_ServiceDesc is the grpc.ServiceDesc for DataKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.DataKeeper",
	HandlerType: (*DataKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Replicate",
			Handler:    _DataKeeper_Replicate_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _DataKeeper_DeleteFile_Handler,
		},
		{
			MethodName: "Wipe",
			Handler:    _DataKeeper_Wipe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dfs.proto",
}
